class GameData {
    constructor() {
        this.revenue = 0;
        this.dau = 0;       // Daily Active Users
        this.arpdau = 0.05; // Base Average Revenue Per DAU per day
        
        // Define all initial upgrades and their initial state
        this.upgrades = {
            acquisition1: {
                id: 'acquisition1',
                name: 'App Store Optimization',
                description: 'Increases DAU by 10.',
                baseCost: 50,
                owned: 0,
                baseEffect: 10,
                effectType: 'dau'
            },
            acquisition2: {
                id: 'acquisition2',
                name: 'Influencer Marketing',
                description: 'Increases DAU by 100.',
                baseCost: 500,
                owned: 0,
                baseEffect: 100,
                effectType: 'dau'
            },
            acquisition3: {
                id: 'acquisition3',
                name: 'Viral Campaign',
                description: 'Increases DAU by 500.',
                baseCost: 5000,
                owned: 0,
                baseEffect: 500,
                effectType: 'dau'
            },
            monetization1: {
                id: 'monetization1',
                name: 'Rewarded Video Ads',
                description: 'Increases ARPDAU by $0.02.',
                baseCost: 100,
                owned: 0,
                baseEffect: 0.02,
                effectType: 'arpdau'
            },
            monetization2: {
                id: 'monetization2',
                name: 'Battle Pass Feature',
                description: 'Increases ARPDAU by $0.10.',
                baseCost: 1500,
                owned: 0,
                baseEffect: 0.10,
                effectType: 'arpdau'
            },
            monetization3: {
                id: 'monetization3',
                name: 'Gacha Mechanics',
                description: 'Increases ARPDAU by $0.50.',
                baseCost: 10000,
                owned: 0,
                baseEffect: 0.50,
                effectType: 'arpdau'
            }
        };

        this.lastSaveTime = Date.now();
    }

    // Math & Scaling: Upgrades follow exponential cost scaling: Cost = BaseCost * (1.15 ^ Owned)
    getUpgradeCost(upgradeId) {
        const upgrade = this.upgrades[upgradeId];
        if (!upgrade) return Infinity;
        return Math.floor(upgrade.baseCost * Math.pow(1.15, upgrade.owned));
    }

    // Helper to process buying an upgrade
    buyUpgrade(upgradeId) {
        const cost = this.getUpgradeCost(upgradeId);
        if (this.revenue >= cost) {
            this.revenue -= cost;
            const upgrade = this.upgrades[upgradeId];
            upgrade.owned += 1;
            
            this.recalculateStats();
            return true;
        }
        return false;
    }

    // Recalculates stats whenever an upgrade is bought or state changes
    recalculateStats() {
        let newDau = 0; // Starts at 0, generated by upgrades
        let newArpdau = 0.05; // Base ARPDAU
        
        for (const key in this.upgrades) {
            const upg = this.upgrades[key];
            if (upg.effectType === 'dau') {
                newDau += (upg.baseEffect * upg.owned);
            } else if (upg.effectType === 'arpdau') {
                newArpdau += (upg.baseEffect * upg.owned);
            }
        }
        
        this.dau = newDau;
        this.arpdau = newArpdau;
    }

    // Number formatting utility for UI rendering
    static formatNumber(num) {
        if (isNaN(num)) return "0";
        if (num < 1000) return Number.isInteger(num) ? num.toString() : num.toFixed(2);
        
        const suffixes = ["", "K", "M", "B", "T", "Qa", "Qi"];
        const magnitude = Math.floor(Math.log10(num) / 3);
        const scaled = num / Math.pow(1000, magnitude);
        
        return parseFloat(scaled.toFixed(2)) + suffixes[magnitude];
    }
}

// Module export for browser environment
window.GameData = GameData;
